vim.o.autoindent = true
vim.o.backspace = "indent,eol,start"
vim.o.backup = false
vim.o.breakindent = true
vim.o.clipboard = "unnamedplus"
vim.o.conceallevel = 0
vim.o.expandtab = true
vim.o.fillchars = "eob: "
vim.o.hlsearch = false
vim.o.ignorecase = true
vim.o.linebreak = true
vim.o.mouse = "a"
vim.o.numberwidth = 4
vim.o.pumheight = 5
vim.o.relativenumber = true
vim.o.smartcase = true
vim.o.smartindent = true
vim.o.scrolloff = 8
vim.o.shiftwidth = 2
vim.o.showmode = false
vim.o.sidescrolloff = 12
vim.o.softtabstop = 2
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.swapfile = false
vim.o.tabstop = 2
vim.o.termguicolors = true
vim.o.timeoutlen = 250
vim.o.undofile = true
vim.o.updatetime = 250
vim.o.wrap = false
vim.o.writebackup = false

vim.wo.cursorline = true
vim.wo.number = true
vim.wo.signcolumn = "yes"

vim.opt.completeopt = "menuone,preview"

